application: user-signup
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
  #upload: favicon\.ico

- url: /.*
  script: main.app

libraries:

- name: jinja2
  version: latest
